---
- name: Install unzip
  yum:
    name: unzip
    state: latest

- name: Download vault
  get_url:
    url: "{{ vault_download_url }}"
    dest: "{{ vault_download_dir }}"
    checksum: "{{ vault_download_checksum }}"

- name: Unpack vault
  unarchive:
    copy: no
    src: "{{ vault_download_dir }}/{{ vault_download_file }}"
    dest: "{{ vault_install_dir }}"
    creates: "vault"
    owner: root
    group: root
    mode: 0755

- name: Create vault config directories
  file:
    path: "/etc/vault.d"
    state: directory

- name: Create vault config files
  template:
    src: "server.hcl.j2"
    dest: "/etc/vault.d/server.hcl"
    mode: 0644
  notify:
  - Restart vault

- name: Add vault systemd unit
  template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service
    mode: 0644
  notify:
  - Reload systemd
  - Restart vault

- name: Install postgres
  yum:
    name: postgresql
    state: latest

- name: Place the vaultsetup.sql script
  template:
    src: vault-table.sql.j2
    dest: /tmp/vaultsetup.sql
    mode: 0600

- name: Run Postgres creation script
  shell: PGPASSWORD={{vault_postgres_password}} psql -h {{vault_postgres_endpoint | replace(':5432','')}} -U {{vault_postgres_username}} vault -f /tmp/vaultsetup.sql